# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(900, 411)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(0, 0))
        Frame.setMaximumSize(QtCore.QSize(931, 411))
        Frame.setStyleSheet("background:none;\n"
"background-color:none")
        Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Main_Frame = QtWidgets.QFrame(parent=Frame)
        self.Main_Frame.setGeometry(QtCore.QRect(0, 0, 931, 411))
        self.Main_Frame.setStyleSheet("QFrame{\n"
"    background-color:rgb(102, 112, 255);\n"
"}")
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.Title_Bar = QtWidgets.QWidget(parent=self.Main_Frame)
        self.Title_Bar.setGeometry(QtCore.QRect(0, 0, 901, 31))
        self.Title_Bar.setStyleSheet("QWidget{\n"
"    background-color:rgb(69, 69, 255)\n"
"}")
        self.Title_Bar.setObjectName("Title_Bar")
        self.CloseButton = QtWidgets.QPushButton(parent=self.Title_Bar)
        self.CloseButton.setGeometry(QtCore.QRect(870, 0, 31, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(12)
        self.CloseButton.setFont(font)
        self.CloseButton.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(87, 109, 255)\n"
"}")
        self.CloseButton.setObjectName("CloseButton")
        self.MinButton = QtWidgets.QPushButton(parent=self.Title_Bar)
        self.MinButton.setGeometry(QtCore.QRect(840, 0, 31, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(22)
        font.setBold(False)
        self.MinButton.setFont(font)
        self.MinButton.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(87, 109, 255)\n"
"}")
        self.MinButton.setObjectName("MinButton")
        self.CpuUsageWidget = QtWidgets.QWidget(parent=self.Main_Frame)
        self.CpuUsageWidget.setGeometry(QtCore.QRect(80, 100, 281, 281))
        self.CpuUsageWidget.setStyleSheet("QWidget{\n"
"background-color:none;\n"
"border-radius:135px;\n"
"border:9px;\n"
"border-style:solid;\n"
"border-top-color:rgb(82, 2, 255);\n"
"border-right-color:rgb(82, 2, 255);\n"
"border-left-color:rgb(82, 2, 255);\n"
"border-bottom-color:rgb(102, 112, 255);\n"
"}")
        self.CpuUsageWidget.setObjectName("CpuUsageWidget")
        self.CpuNameLabel = QtWidgets.QLabel(parent=self.CpuUsageWidget)
        self.CpuNameLabel.setGeometry(QtCore.QRect(60, 240, 161, 21))
        self.CpuNameLabel.setStyleSheet("border:none;\n"
"border-radius:7px;\n"
"background-color:rgb(66, 73, 165);\n"
"color:white")
        self.CpuNameLabel.setText("")
        self.CpuNameLabel.setObjectName("CpuNameLabel")
        self.label_cpu = QtWidgets.QLabel(parent=self.CpuUsageWidget)
        self.label_cpu.setGeometry(QtCore.QRect(0, 90, 281, 101))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(48)
        font.setBold(True)
        self.label_cpu.setFont(font)
        self.label_cpu.setStyleSheet("background-color:none;\n"
"border:none;\n"
"color:white")
        self.label_cpu.setText("")
        self.label_cpu.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_cpu.setObjectName("label_cpu")
        self.memUsageWidget = QtWidgets.QWidget(parent=self.Main_Frame)
        self.memUsageWidget.setGeometry(QtCore.QRect(530, 100, 281, 281))
        self.memUsageWidget.setStyleSheet("QWidget{\n"
"background-color:none;\n"
"border-radius:135px;\n"
"border:9px;\n"
"border-style:solid;\n"
"border-top-color:rgb(82, 2, 255);\n"
"border-right-color:rgb(82, 2, 255);\n"
"border-left-color:rgb(82, 2, 255);\n"
"border-bottom-color:rgb(102, 112, 255);\n"
"}")
        self.memUsageWidget.setObjectName("memUsageWidget")
        self.RamTotal = QtWidgets.QLabel(parent=self.memUsageWidget)
        self.RamTotal.setGeometry(QtCore.QRect(60, 240, 161, 20))
        self.RamTotal.setStyleSheet("border:none;\n"
"border-radius:7px;\n"
"background-color:rgb(66, 73, 165);\n"
"color:rgb(255, 255, 255)")
        self.RamTotal.setText("")
        self.RamTotal.setObjectName("RamTotal")
        self.label_ram = QtWidgets.QLabel(parent=self.memUsageWidget)
        self.label_ram.setGeometry(QtCore.QRect(0, 90, 281, 101))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(48)
        font.setBold(True)
        self.label_ram.setFont(font)
        self.label_ram.setStyleSheet("background-color:none;\n"
"border:none;\n"
"color:white")
        self.label_ram.setText("")
        self.label_ram.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ram.setObjectName("label_ram")
        self.RamUsed = QtWidgets.QLabel(parent=self.memUsageWidget)
        self.RamUsed.setGeometry(QtCore.QRect(60, 210, 161, 20))
        self.RamUsed.setStyleSheet("border:none;\n"
"border-radius:7px;\n"
"background-color:rgb(66, 73, 165);\n"
"color:rgb(255, 255, 255)")
        self.RamUsed.setText("")
        self.RamUsed.setObjectName("RamUsed")
        self.label_3 = QtWidgets.QLabel(parent=self.Main_Frame)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 241, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(26)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.Main_Frame)
        self.label_4.setGeometry(QtCore.QRect(550, 60, 241, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(26)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.CloseButton.setText(_translate("Frame", "X"))
        self.MinButton.setText(_translate("Frame", "-"))
        self.label_3.setText(_translate("Frame", "CPU"))
        self.label_4.setText(_translate("Frame", "RAM"))
